//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bank_Branch()
        {
            this.User_Bank_Branch = new HashSet<User_Bank_Branch>();
        }
    
        public string Branch_Code { get; set; }
        public string Branch_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Bank_Branch> User_Bank_Branch { get; set; }
    }
}
