//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporate_User
    {
        public string User_Corporate_Id { get; set; }
        public string Username { get; set; }
        public string Corporate_Type { get; set; }
    
        public virtual Corporate Corporate { get; set; }
        public virtual User User { get; set; }
    }
}
