//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISWEntities : DbContext
    {
        public ISWEntities()
            : base("name=ISWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank_Branch> Bank_Branches { get; set; }
        public virtual DbSet<Corporate> Corporates { get; set; }
        public virtual DbSet<Corporate_User> Corporate_Users { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Bank_Branch> User_Bank_Branches { get; set; }
        public virtual DbSet<User_Institution> User_Institutions { get; set; }
        public virtual DbSet<User_Role> User_Roles { get; set; }
    }
}
