//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Institution
    {
        public string User_Institution1 { get; set; }
        public string Username { get; set; }
        public string Institution_Code { get; set; }
    
        public virtual Institution Institution { get; set; }
        public virtual User User { get; set; }
    }
}
