//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role
    {
        public string User_Role_ID { get; set; }
        public string Username { get; set; }
        public string Role_Code { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
